# Certificate Generator - External Nginx & PostgreSQL Setup
# Uses your existing nginx and PostgreSQL

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5433}/${POSTGRES_DB:-certificate_generator}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DEBUG=false
      - DEFAULT_ADMIN_USERNAME=${DEFAULT_ADMIN_USERNAME:-admin}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD:-admin123}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - API_DOMAIN=${API_DOMAIN}
    volumes:
      - ./certs:/app/certs:ro
      - ./certs_output:/app/certs_output
    ports:
      - "5003:5003"  # Expose backend port for your nginx to proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=/api
    ports:
      - "5001:80"  # Expose frontend port for your nginx to serve
    restart: unless-stopped
    depends_on:
      - backend
